version: "3.7"

services:
  account-lookup-service-int:
    image: mojaloop/account-lookup-service-int:local
    build:
      context: .
      target: builder
      cache_from:
        - mojaloop/account-lookup-service
        - account-lookup-service
    container_name: als_account-lookup-service-int
    user: root
    networks:
      - als-mojaloop-net
    command:
      - sh
      - -c
      - "tail -f /dev/null"
    depends_on:
      - mysql-als
      - central-ledger
    volumes:
      - ./src:/opt/app/src
      - ./secrets:/opt/app/secrets
      - ./test:/opt/app/test
      - ./package.json:/opt/app/package.json
      - ./test/integration-config.json:/opt/app/config/default.json
      - ./docker/wait-for:/opt/wait-for